general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: true

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "5px"

  # Gap between windows and the screen edge.
  outer_gap: "5px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#99ff99"

  inactive:
    enabled: false
    color: "#0f0f0f"

bar:
  height: "38px"
  position: "top"
  opacity: 1.0
  background: "#114411ff"
  foreground: "#99ff99"
  font_family: "Meiryo UI"
  font_size: "13px"
  padding: "8px 8px"
  offset_x: "5px"
  offset_y: "5px"
  border_radius: "6"
  always_on_top: false
  component_separator:
    label: " | "
  components_left:
    - type: "workspaces"
      focused_workspace_background: "transparent"
      focused_workspace_foreground: "#ffffffff"
      displayed_workspace_background: "transparent"
      displayed_workspace_foreground: "#ff0000ff"
      default_workspace_background: "transparent"
      default_workspace_foreground: "#99ff99ff"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    - type: "tiling direction"
      label_horizontal: "â®‚"
      label_vertical: "â®"
      background: "#ffffff33"
      margin: "0 4px"
      padding: "0 8px"
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "weather"
      latitude: 35.177
      longitude: 136.882
      label: "{temperature_celsius}Â°C"
      label_sun: "â˜€ï¸ {temperature_celsius}Â°C"
      label_moon: "ğŸŒ™ {temperature_celsius}Â°C"
      label_cloud_moon: "ğŸŒ™â˜ï¸ {temperature_celsius}Â°C"
      label_cloud_sun: "â›… {temperature_celsius}Â°C"
      label_cloud_moon_rain: "ğŸŒ™ğŸŒ§ï¸ {temperature_celsius}Â°C"
      label_cloud_sun_rain: "ğŸŒ¦ï¸ {temperature_celsius}Â°C"
      label_cloud_rain: "ğŸŒ§ï¸ {temperature_celsius}Â°C"
      label_snow_flake: "â„ï¸ {temperature_celsius}Â°C"
      label_thunderstorm: "âš¡ {temperature_celsius}Â°C"
      label_cloud: "â˜ï¸ {temperature_celsius}Â°C"
    - type: "network"
      label_no_internet: "âœ‚ï¸ "
      label_ethernet: "ğŸš…"
      label_wifi_strength_0: "ğŸ“¶: 0%"
      label_wifi_strength_25: "ğŸ“¶: 25%"
      label_wifi_strength_50: "ğŸ“¶: 50%"
      label_wifi_strength_75: "ğŸ“¶: 75%"
      label_wifi_strength_100: "ğŸ“¶: 100%"
    # - type: "gpu"
    #   label: "ğŸ¨{percent_usage}%"
    #   # How often this counter is refreshed.
      refresh_interval_ms: 1000
    - type: "memory"
      label: "ğŸ‘{percent_usage}%"
      # How often this counter is refreshed.
      refresh_interval_ms: 1000
    - type: "cpu"
      label: "ğŸ§ {percent_usage}%"
      # How often this counter is refreshed.
      refresh_interval_ms: 1000
    - type: "battery"
      label_draining: "ğŸ”‹{battery_level}%"
      label_power_saver: "ğŸª«{battery_level}%"
      label_charging: "âš¡{battery_level}%"
    - type: "volume"
      label_low: "ğŸ”ˆ"
      label_medium: "ğŸ”‰{volume_level}%"
      label_high: "ğŸ”Š"
      label_mute: "ğŸ”‡"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "âŒšHH:mm tt  d ddd MMM yyyy"

workspaces:
  - name: "0"
    display_name: "ğŸš0"
    bind_to_monitor: 1
    keep_alive: true
  - name: "1"
    display_name: "ğŸŒ1"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    display_name: "ğŸš2"
    bind_to_monitor: 1
    keep_alive: true
  - name: "3"
    display_name: "ğŸ†š3"
    bind_to_monitor: 1
    keep_alive: true
  - name: "4"
    display_name: "ğŸ’¬4"
    bind_to_monitor: 1
    keep_alive: true
  - name: "5"
    display_name: "âœ‰5"
    bind_to_monitor: 1
    keep_alive: true
  - name: "6"
    display_name: "ğŸ“–6"
    bind_to_monitor: 1
    keep_alive: true
  - name: "7"
  - name: "8"
  - name: "9"
    display_name: "ğŸ³9"
    bind_to_monitor: 1
    keep_alive: true

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost|GoogleDriveFS|HakkoAI/"

  - command: "ignore"
    match_process_name: "/UriageGenka/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  - command: "move to workspace 1"
    match_process_name: "chrome"
  - command: "move to workspace 1"
    match_process_name: "firefox"
  - command: "move to workspace 1"
    match_process_name: "thorium"
  - command: "move to workspace 1"
    match_process_name: "msedge" # Edge

  - command: "move to workspace 2"
    match_process_name: "WindowsTerminal" # Microsoft Terminal

  - command: "move to workspace 3"
    match_process_name: "Code" # Visual Studio Code

  - command: "move to workspace 4"
    match_process_name: "ms-teams" # Teams

  - command: "move to workspace 5"
    match_process_name: "olk" # Outlook

  - command: "move to workspace 6"
    match_process_name: "CubeChecker" # CubeChecker

  - command: "move to workspace 9"
    match_process_name: "Docker Desktop" # Docker Desktop

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H"]
      - command: "resize width +2%"
        bindings: ["L"]
      - command: "resize height +2%"
        bindings: ["K"]
      - command: "resize height -2%"
        bindings: ["J"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  # Notice: In Excel, This Key is make new line in cell.
  # - command: "exec wt"
  #   binding: "Alt+Enter"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 0"
    binding: "Alt+0"
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 0", "focus workspace 0"]
    binding: "Alt+Shift+0"
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
